name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Navigate to subfolder
        run: cd my-react-app

      - name: Install dependencies
        working-directory: my-react-app
        run: npm install

      - name: Build the app
        working-directory: my-react-app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-react-app/build
